export const styles = {
    container: {
        background: "linear-gradient(118deg, #EB7125 0%, #CB4E00 100.36%)",
        width: '100vw',
        height: '100vh',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
    },
    previous:{
        border:"none",
        backgroundColor:"transparent",
        display: "flex",
        position:"absolute",
        top:"112px",
        right:"131px",
        width: "59px",
        height: "57px",
        flexDirection: "column",
        justifyContent: "center",
        color: "rgba(158, 158, 158, 0.63)",
        textAlign: "center",
        fontFamily: "NanumSquare",
        fontSize: "70px",
        fontStyle: "normal",
        fontWeight: "400",
        lineHeight: "normal",
        cursor:"pointer"
    },
    previous2:{
        border:"none",
        backgroundColor:"transparent",
        display: "flex",
        position:"absolute",
        top:"112px",
        left:"146px",
        right:"1242px",
        width: "59px",
        height: "57px",
        flexDirection: "column",
        justifyContent: "center",
        color: "rgba(158, 158, 158, 0.63)",
        textAlign: "center",
        fontFamily: "NanumSquare",
        fontSize: "70px",
        fontStyle: "normal",
        fontWeight: "400",
        lineHeight: "normal",
        cursor:"pointer"
    },
    logo: {
        position: "relative",
        color: "#EB7125",
        textAlign: "center",
        fontFamily: "Pretendard",
        fontSize: "50px",
        fontStyle: "normal",
        fontWeight: 600,
        lineHeight: "normal",
        letterSpacing: "-5px",
        margin: "128px 0 647px 0",
        display: 'flex',
        flexDirection: 'column',  
        alignItems: 'center',
        justifyContent: 'center'
    },
    toggle: {
        position:"absolute",
        listStyle:"none",
        border: "1px solid #000",
        background: "#FFF",
        width: "195px",
        height: "92px",
        left:"156px",
        top:"125px",
        zIndex: 9999
    },
    bimg:{
        cursor:"pointer"
    },
    buttonimg:{
        cursor:"pointer",
        position: "relative",
        left:"121%",
        top:"75px"
    },
    setProfile:{
        position:"absolute",
        marginTop:"640px"
    },
    defaultProfileImg:{
        position:"absolute",
        left:"-80%",
        top:"-80%",
        width:"192px",
        height:"197px"
    },
    text:{
        position:"absolute",
        top: "740px",
        left:"39%",
        textAlign: 'center',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        // flexDirection: 'column' 
    },
    text1: {
        color: "#000",
        fontFamily: "Pretendard",
        fontSize: "22px",
        fontStyle: "normal",
        fontWeight: 500,
        lineHeight: "normal"
    },

    text2: {
        color: "#EB7125",
        fontFamily: "Pretendard",
        fontSize: "22px",
        fontStyle: "normal",
        fontWeight: 500,
        lineHeight: "normal",
        cursor:"pointer",
        textDecoration:"none"
    },

    buttonBox: {
        textAlign: 'center',
        display: 'flex',
        flexDirection: 'column',  
        alignItems: 'center',
        justifyContent: 'center'
    },

    button1: {
        borderRadius: "40px",
        border: "none",
        background:"#00C73C",
        color: "#FFF",
        textAlign: "center",
        fontFamily: "Pretendard",
        fontSize: "28px",
        fontStyle: "normal",
        fontWeight: 600,
        lineHeight: "normal",
        position:"absolute",
        margin: '81px',  
        width: "552px",
        height: "90px",
        top:"269px",
        left:"30%",
        cursor:"pointer"
    },
    button2: {
        position:"absolute",
        // margin: '43px',  
        borderRadius: '40px',
        background: "#FFD740",
        color: "#424242",
        textAlign: "center",
        fontFamily: "Pretendard",
        fontSize: "28px",
        fontStyle: "normal",
        fontWeight: 600,
        lineHeight: "normal",
        border:"none",
        width: "552px",
        height: "90px",
        top:"402px",
        margin: '81px',  
        cursor:"pointer",
        left:"30%"
    },
    button3: {
        position:"absolute",
        color: "#424242",
        textAlign: "center",
        fontFamily: "Pretendard",
        fontSize: "28px",
        fontStyle: "normal",
        fontWeight: 600,
        lineHeight: "normal",
        // margin: '43px',  
        borderRadius: '40px',
        background: "#EEE",
        border:"none",
        width: "552px",
        height: "90px",
        top:"535px",
        left:"30%",
        margin: '81px',  
        cursor:"pointer"
    },
    pageTitle:{
        color: "#000",
        textAlign: "center",
        fontFamily: "Pretendard",
        fontSize: "48px",
        fontStyle: "normal",
        fontWeight: 600,
        lineHeight: "normal",
        position:"absolute",
        marginTop:"338px"
    },
    nextButton: {
        position:"absolute",
        border:"none",
        marginTop:"1035px",
        width: '324px',  
        height: '77px',
        borderRadius: '40px',
        background: '#EB7125',
        cursor:"pointer",
        color:"#FFF",
        textAlign:"center",
        fontSize:"40px",
        fontStyle:"normal",
        fontFamily:"Pretendard",
        fontWeight:500
    },
    loginButton: {
        border:"none",
        position:"absolute",
        marginTop:"1035px",
        width: '324px',  
        height: '77px',
        borderRadius: '40px',
        background: '#EB7125',
        color:"#FFF",
        textAlign:"center",
        fontSize:"40px",
        fontStyle:"normal",
        fontFamily:"Pretendard",
        fontWeight:500,
        cursor:"pointer"
    },
    whitebox: {
        borderRadius: "20px",
        background: "#FFF",
        boxShadow: "0px 4px 4px 0px rgba(0, 0, 0, 0.25)",
        width: '86.25%',
        height: '81.54%'
    },
    bar: {
        position:"absolute",
        marginTop: '700px',
        width: '934px',
        height: '90px',
        borderRadius: "40px",
        border: "2px solid #000",
        color: "rgba(0, 0, 0, 0.50)",
        fontFamily: "Pretendard",
        fontSize: "30px",
        fontStyle: "normal",
        fontWeight: 400,
        lineHeight: "normal"
    },
    bar2: {
        position:"absolute",
        marginTop: '700px',
        width: '934px',
        height: '90px',
        borderRadius: "40px",
        border: "2px solid #000",
        color: "rgba(0, 0, 0, 0.50)",
        fontFamily: "Pretendard",
        fontSize: "30px",
        fontStyle: "normal",
        fontWeight: 400,
        lineHeight: "normal"
    }
};
